### ISSUE TITLE
Error in bitbucket usage

### ISSUE THREAD

**Issue by jarodium** [jacobkiers/OAuth#7]
Hello when using this lib with bitbucket API i get the following fatal error

PHP Fatal error:  Can't inherit abstract function JacobKiers\\OAuth\\SignatureMethod\\SignatureMethodInterface::getName() (previously declared abstract in JacobKiers\\OAuth\\SignatureMethod\\SignatureMethod) in /var/www/ideiasfrescas/data/www/seed.ideiasfrescas.com/vendor/jacobkiers/oauth/src/JacobKiers/OAuth/SignatureMethod/SignatureMethod.php on line 29

**Comment by jacobkiers** [comment]
Hi @jarodium, thank you for reporting this. I'll see if I can get around to fixing it during the week end.

Or, if you fixed it already, I'd also appreciate a PR :smile:.

**Comment by jarodium** [comment]
Hello, I think I have solved this ssue.
I was using php 5.3, but upon moving the app to a hosting account with php 5.4 it works.

Dunno if php >= 5.4 is specifically required also for this lib, but I thought you should know about it.

**Comment by jacobkiers** [comment]
Thank you for writing that up. I will check it, and if it is, I'll also update the PHP version requirement in `composer.json`.

**Comment by jacobkiers** [comment]
@jarodium Do you know the exact PHP version and OS you were using with PHP 5.3? It seems related to [PHP bug 43200](https://bugs.php.net/bug.php?id=43200), which was fixed in PHP 5.3.9.

**Comment by jacobkiers** [comment]
@jarodium Fixed in version 1.0.12.

**Comment by jarodium** [comment]
Yes it was 5.3.3 to be exact
